version: '3.8'

services:
  db:
    container_name: my-postgres
    image: postgres
    environment:
      POSTGRES_USER: ayoub  # Replace with your database user
      POSTGRES_PASSWORD: password  # Replace with your database password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/your_database
      SPRING_DATASOURCE_USERNAME: ayoub  # Replace with the same user as POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: password  # Replace with the same password as POSTGRES_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped

networks:
  db:

volumes:
  db:
